version: '3'
services:
  app:
    image: first-service
    container_name: first-service
    build:
      context: src/main/java
      dockerfile: Dockerfile
    ports:
      - "8089:8089"  # Mapping Spring Boot app's port
    environment:
      - SPRING_REDIS_HOST=redis  # Tell Spring Boot to connect to Redis container
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/testdb  # H2 DB path inside container
      - SPRING.H2.CONSOLE.SETTINGS.WEB-ALLOW-OTHERS=true
    depends_on:
      - redis
    volumes:
      - ./data:/app/data  # Mount a volume for H2 data persistence
      - c:/data:/app/data/test
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"  # Mapping Redis port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
