apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-data-pvc  # PVC name referred in Deployment
spec:
  accessModes:
    - ReadWriteOnce  # Allows single-node read/write
  resources:
    requests:
      storage: 1Gi  # Storage size request for the volume
